import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Main = dynamic(() => 
  import('./mainpage')
, {
  ssr: false
});

export default function Home() {

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 9000)
  }, [])

  if (isLoading) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zhen Yang&apos;s Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/me-circle.png" />
        </Head>
        <main className={styles.main}>
          <div className={styles.video_container}>
            <video autoPlay muted>
              <source src='/loading-animation.mp4' type='video/mp4'/>
            </video>
          </div>
        </main>
      </div>
    )
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zhen Yang&apos;s Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/me-circle.png" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;1,900&display=swap" rel="stylesheet"></link>
        </Head>
        <Main />
      </div>
    )
  }
}